name: split

on: [push]

jobs:
  test:
    strategy:
      matrix:
        ruby: ["3.5.0-preview1", "3.4", "3.3", "3.2", "3.1", "3.0", "2.7"]
        rails: ["8.0", "7.2", "7.1", "6.1"]
        exclude:
          - rails: "6.1"
            ruby: "3.4"

          - rails: "6.1"
            ruby: "3.5.0-preview1"

          - rails: "7.2"
            ruby: "2.7"
          - rails: "7.2"
            ruby: "3.0"

          - rails: "8.0"
            ruby: "2.7"
          - rails: "8.0"
            ruby: "3.0"
          - rails: "8.0"
            ruby: "3.1"
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports: ["6379:6379"]
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_VERSION: ${{ matrix.rails }}
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install dependencies
        run: |
          bundle install --jobs 4 --retry 3

      - name: Display Ruby version
        run: ruby -v

      - name: Test
        run: bundle exec rspec
        env:
          REDIS_URL: redis:6379

      - name: Rubocop
        run: bundle exec rubocop
